<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request as GuzzleRequest;
use GuzzleHttp\Psr7\Stream;

class SenderController extends Controller
{
    //

    public function sendPay(Request $request)
    {
        // Data generated by system
        $transcreatetime = date('Ymdhis');
        $mcc_code = $request->secondary_merchant_industry;
        // Get config data by ID
        $configid = $request->config_id;
        $configData =  DB::table('tblAlibaba_ASP')
                        ->select(
                          'tblAlibaba_ASP_SecondMerchantID as secondary_merchant_id','tblAlibaba_ASP_SecondMerchantName as secondary_merchant_name',
                          'tblAlibaba_ASP_TerminalID as terminal_id','tblAlibaba_ASP_MCC_Code as secondary_merchant_industry')
                        ->where('tblAlibaba_ASP_ID','=',$configid)
                        ->first();
        // convert to json string
        $json = json_encode($configData);

        $arrValues = [];
        // construct pre-signed string
        foreach($request->json() as $index => $value)
        {
            if($index == 'secondary_merchant_industry' OR $index == 'config_id' OR $index == 'trx_type')
            {
              unset($index);
            } else {
              array_push($arrValues,$index."=".$value);
            }

        }
        // push some data to array
        array_push($arrValues,'trans_create_time='.$transcreatetime,'extend_info='.$json);
        // sort array by value ascending
        sort($arrValues);
        // implode the array to become string and using delimiter of '&'
        // $imploded = 'sign=aaczziabnm9w3sr23wu2zhevd7u8n1hx&';
        $imploded = implode($arrValues,'&');
        // $imploded .= '&sign=aaczziabnm9w3sr23wu2zhevd7u8n1hx';
        // sign the pre-signed string
        $sign = md5($imploded);
        // $sign = 'aaczziabnm9w3sr23wu2zhevd7u8n1hx';
        $signtype = 'MD5';

        array_push($arrValues, 'sign='.$sign, 'sign_type='.$signtype);

        $client = new Client();
        $promise = $client->post('http://dev17.revpay.com.my:8000/api/request',[
            'timeout' => '15',
            'headers' => [
              'Content-Type' => 'application/json',
              'Accept' => 'application/json',
            ],
            'json' => [
              "trx_type" => $request->trx_type,
              "_input_charset" => $request->_input_charset,
              "config_id" => $configid,
              "service" => $request->service,
              "partner" => $request->partner,
              "alipay_seller_id" => $request->alipay_seller_id,
              "partner_trans_id" => $request->partner_trans_id,
              "currency" => $request->currency,
              "trans_amt" => $request->trans_amt,
              "trans_name" => $request->trans_name,
              "buyer_identity_code" => $request->buyer_identity_code,
              "identity_code_type" => $request->identity_code_type,
              "memo" => $request->memo,
              "secondary_merchant_industry" => $request->secondary_merchant_industry,
              "biz_product" => $request->biz_product,
              "trans_create_time" => $transcreatetime,
              "sign" => $sign,
              "sign_type" => $signtype
            ]
        ]);
        
        $urlreq = implode($arrValues,'&');
        // production
        // $req = new GuzzleRequest('GET','https://intlmapi.alipay.com/gateway.do?'.$urlreq,[
        //   'headers' => ['Accept' => 'application/xml', 'Content-Type' => 'text/xml']
        // ]);
        // testing
        $req = new GuzzleRequest('POST','https://openapi.alipaydev.com/gateway.do?'.$urlreq,[
          'headers' => ['Accept' => 'application/xml', 'Content-Type' => 'text/xml']
        ]);
        $promise1 = $client->sendAsync($req);
        $promise1->then(function($response){
            echo $response->getBody();
        });
        $promise1->wait();
        // $aliResponse = simplexml_load_file('https://intlmapi.alipay.com/gateway.do?'.$urlreq);
        // echo var_dump($aliResponse);

    }
}
